CREATE TABLE IF NOT EXISTS public.hits
(
    id          bigint                      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    application character varying(512)      NOT NULL,
    uri         character varying(512)      NOT NULL,
    remote_ip   character varying(255)      NOT NULL,
    date_time   timestamp without time zone NOT NULL,
    CONSTRAINT stats_pkey PRIMARY KEY (id)
);